#+TITLE: Dotfiles
#+AUTHOR: Sebastian Tunberg
#+LANGUAGE: en

* Table of Contents                                            :noexport:TOC:
- [[#about][About]]
- [[#my-toolbox][My Toolbox]]
- [[#setup][Setup]]

* About
This repository contains my systems setup.
I have three hosts set up by this repository:
- A Lenovo laptop running [[https://nixos.org/][NixOS]]
- The same Lenovo laptop running [[https://www.debian.org/][GNU/Linux debian]]. This setup is kept as a reference - I don't use it myself any longer.
- A Macbook running macOS
I use [[https://nixos.org/][nix]] as package manager for all hosts.
I use [[https://github.com/nix-community/home-manager][Home Manager]] to declare nix packages and configuration to use.
For the macbook I additionally use [[https://github.com/LnL7/nix-darwin][nix-darwin]] to set up system packages and fonts.
All hosts are configured from their respective [[/hosts][/hosts]] directory, [[hosts/common.nix][hosts/common.nix]] contain shared configuration and program-specific configuration live under [[/programs/][/programs/]]
* Questions or assistance
I am happy to answer any questions about the contents of this repository or get newcomers started in the world of nix! Send me a message on Discord: sebastiant#6342
* My toolbox
- [[https://www.gnu.org/software/emacs/][GNU Emacs]] with plugins such as projectile, magit, org-mode, lsp-mode and more
- [[https://swaywm.org][Sway]] as compositor
- [[https://www.zsh.org/][Zsh]] with [[https://ohmyz.sh/][Oh My Zsh]] as shell
- [[https://github.com/alacritty/alacritty][Alacritty]] as terminal emulator
- Appearance-wise i use [[https://github.com/be5invis/Iosevka][Iosevka]] as my default font. The great [[https://github.com/protesilaos/modus-themes][Modus themes]] for Emacs  and otherwise [[https://ethanschoonover.com/solarized/][Solarized dark]] theme

* Setup
- [[https://nixos.org/manual/nix/stable/#sect-multi-user-installation][Install nix]] and set up flakes
- Clone this repository
  #+begin_src shell
  $ git clone git@github.com:sebastiant/dotfiles.git
  $ cd dotfiles
  #+end_src
- Change name, username and email if you're not me
  #+begin_src shell
  $ grep sebastian -r .
  $ # edit away!
  #+end_src
- Create the first generation
  - NixOS
    #+begin_src shell
      $ nixos-rebuild switch --upgrade --flake '.#t14' --use-remote-sudo
    #+end_src
    Or if system hostname is set to nixosConfigurations.<hostname> in flake.nix outputs:
    #+begin_src shell
      $ nixos-rebuild switch --upgrade --flake '.#' --use-remote-sudo
    #+end_src
  - Linux
    I don't use this any longer and it is only kept for reference.
    #+begin_src shell
    $ nix build && ./result/activate
    #+end_src
  - macOS
    #+begin_src shell
    $ nix build && sudo ./result/activate
    #+end_src
# End:
