ZSH_CUSTOM=$HOME/.config/oh-my-zsh

CASE_SENSITIVE="true"

DISABLE_AUTO_TITLE="true"

COMPLETION_WAITING_DOTS="true"

# User configuration
alias ls="ls -lF"

export EDITOR="emacsclient -nw"
export VISUAL=$EDITOR

export TERM="xterm-256color"

setopt interactivecomments

export PATH="$PATH:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$HOME/.local/bin:$HOME/.cargo/bin"

# For stuff not suppose to be version controlled
if [ -e ~/.env_custom ]; then
  source ~/.env_custom
fi

if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
  exec sway
fi
